_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 41
                - 50
            "2":
                - 1
                - 41
                - 50
            "3":
                - 1
                - 13
                - 15
                - 16
                - 55
            "4": 3.11.0
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
augmentation:
    value:
        normalize:
            mean:
                - 0.485
                - 0.456
                - 0.406
            std:
                - 0.229
                - 0.224
                - 0.225
        random_horizontal_flip: 0.5
        random_rotation: 10
batch_size:
    value: 256
data:
    value:
        batch_size: 256
        input_size: 48
        num_classes: 15
        num_workers: 6
        val_batch_size: 64
experiment:
    value:
        device: cuda
        name: deep_pro_experiment
        num_epochs: 200
        seed: 777
learning_rate:
    value: 0.001
logging:
    value:
        log_freq: 10
        project_name: deep_pro_experiments
        save_model: true
        use_wandb: true
model:
    value: InceptionResNetModel
model_save:
    value:
        save_best: true
        save_dir: ./checkpoints
        save_last: true
num_epochs:
    value: 200
optimizer:
    value: Adam
scheduler:
    value: StepLR
training:
    value:
        criterion: crossentropy
        deterministic: true
        print_freq: 50
