defaults:
  - model: resnet152_se
  - _self_

# Experiment settings
experiment:
  name: "deep_pro_experiment_v2"
  seed: 777
  num_epochs: 100  # 조기 종료 예방
  device: "cuda"

# Data settings
data:
  batch_size: 256
  val_batch_size: 64
  num_workers: 6
  num_classes: 15
  input_size: 48

# Training settings
training:
  criterion: "crossentropy"
  print_freq: 50
  deterministic: true

# Optimizer settings (fixed)
optimizer:
  _target_: torch.optim.Adam
  lr: 0.005
  weight_decay: 0.005 
  betas: [0.9, 0.999]

# Scheduler settings (fixed) - 더 부드러운 감소
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 100  # num_epochs와 일치
  eta_min: 0.00001  # 최소 학습률

# Logging settings
logging:
  use_wandb: true
  project_name: "deep_pro_experiments"
  log_freq: 10
  save_model: true

# Data preprocessing (only normalization)
data_preprocessing:
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Model save settings
model_save:
  save_dir: "./checkpoints"
  save_best: true
  save_last: true