defaults:
  - model: se_resnet
  - _self_

# Experiment settings
experiment:
  name: "deep_pro_experiment"
  seed: 777
  num_epochs: 50
  device: "cuda"

# Data settings
data:
  batch_size: 256
  val_batch_size: 64
  num_workers: 6
  num_classes: 15
  input_size: 48

# Training settings
training:
  criterion: "crossentropy"
  print_freq: 50
  deterministic: true

# Optimizer settings (fixed)
optimizer:
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0.0001
  betas: [0.9, 0.999]

# Scheduler settings (fixed)
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 20
  gamma: 0.1

# Logging settings
logging:
  use_wandb: true
  project_name: "deep_pro_experiments"
  log_freq: 10
  save_model: true

# Data augmentation
augmentation:
  random_horizontal_flip: 0.5
  random_rotation: 10
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Model save settings
model_save:
  save_dir: "./checkpoints"
  save_best: true
  save_last: true